### PR TITLE
Reification is not supported outside macro

### PR DESCRIPTION
**Pull request by kLabz**
https://github.com/HaxeFoundation/haxe/issues/10883

### CODE REVIEW

**Comment by joshtynjala** [comment]
@Simn Can we get a new hxargs release that includes this fix?

**Comment by joshtynjala** [comment]
This is affecting Feathers UI users trying to use Haxe 4.3. They cannot create a new project on the command line with `haxelib run feathersui new-project`. I've had to tell multiple users to downgrade to Haxe 4.2.5 for now. I hope that a new Haxelib release is on the horizon!

**Comment by Simn** [comment]
I've pushed https://lib.haxe.org/p/hxargs/4.0.0/

**Comment by joshtynjala** [comment]
@Simn Thank you!

**Pull request merged**
